export type GearId = "guitar" | "amp" | "automation" | "merch" | "distribution";
export const GEAR: {
  id: GearId;
  name: string;
  label: string;
  description: string;
  cost: number;
  passive: number;
  click: number;
  icon: string;
}[] = [
  {
    id: "guitar",
    name: "Junkyard strings",
    label: "INSTRUMENTS",
    description: "Six strings. Zero safety regulations.",
    cost: 15,
    passive: 0.3,
    click: 1,
    icon: "guitar",
  },
  {
    id: "amp",
    name: "Overdrive stack",
    label: "AMPLIFICATION",
    description: "Make the neighbors part of your fanbase.",
    cost: 150,
    passive: 2,
    click: 3,
    icon: "amp",
  },
  {
    id: "automation",
    name: "Riff replicator",
    label: "AUTOMATION",
    description: "Your riffs. On repeat. Without the sleep.",
    cost: 1500,
    passive: 12,
    click: 0,
    icon: "cpu",
  },
  {
    id: "merch",
    name: "Bootleg merch lab",
    label: "MERCHANDISE",
    description: "Wear the rebellion. Preferably in black.",
    cost: 18000,
    passive: 80,
    click: 0,
    icon: "shirt",
  },
  {
    id: "distribution",
    name: "Pirate broadcast",
    label: "DISTRIBUTION",
    description: "Hijack the airwaves. Find your people.",
    cost: 180000,
    passive: 500,
    click: 0,
    icon: "radio",
  },
];
export type Role = "drums" | "bass" | "vocals" | "synth";
export const ROLES: Role[] = ["drums", "bass", "vocals", "synth"];
export const MUSICIANS: {
  id: string;
  name: string;
  role: Role;
  title: string;
  cost: number;
  passive: number;
  credit: number;
  fans: number;
  album: number;
  color: string;
}[] = [
  {
    id: "hex",
    name: "Hex",
    role: "drums",
    title: "Chrome knuckles. Human heartbeat.",
    cost: 100,
    passive: 2,
    credit: 0.1,
    fans: 0,
    album: 0,
    color: "#eea168",
  },
  {
    id: "crash",
    name: "Crash",
    role: "drums",
    title: "Every beat starts a small riot.",
    cost: 100,
    passive: 2,
    credit: 0,
    fans: 0.2,
    album: 0,
    color: "#e38eac",
  },
  {
    id: "volt",
    name: "Volt",
    role: "bass",
    title: "Low frequencies. High voltage.",
    cost: 1800,
    passive: 8,
    credit: 0.15,
    fans: 0,
    album: 0,
    color: "#b6adfa",
  },
  {
    id: "echo",
    name: "Echo",
    role: "bass",
    title: "A pulse the underground remembers.",
    cost: 1800,
    passive: 8,
    credit: 0,
    fans: 0.25,
    album: 0,
    color: "#6cdccf",
  },
  {
    id: "nyx",
    name: "Nyx",
    role: "vocals",
    title: "A voice that cuts through concrete.",
    cost: 16000,
    passive: 25,
    credit: 0,
    fans: 0.35,
    album: 0,
    color: "#dbde6b",
  },
  {
    id: "razor",
    name: "Razor",
    role: "vocals",
    title: "One take. No second chances.",
    cost: 16000,
    passive: 25,
    credit: 0.15,
    fans: 0,
    album: 0.2,
    color: "#fd9e91",
  },
  {
    id: "zero",
    name: "Zero",
    role: "synth",
    title: "Machine precision. Analog soul.",
    cost: 95000,
    passive: 70,
    credit: 0,
    fans: 0,
    album: 0.35,
    color: "#7fbfe9",
  },
  {
    id: "glitch",
    name: "Glitch",
    role: "synth",
    title: "Turn the system error up to eleven.",
    cost: 95000,
    passive: 70,
    credit: 0.25,
    fans: 0.1,
    album: 0,
    color: "#d1a0eb",
  },
];
export const VENUES = [
  {
    name: "The Rehearsal Room",
    short: "Rehearsal room",
    district: "SECTOR 07 · THE UNDERCITY",
    tag: "HUMBLE BEGINNINGS",
    fans: 0,
    gear: 0,
    duration: 60,
    credits: 120,
    reward: 30,
    description: "A borrowed garage. A busted amp. A very loud beginning.",
    gig: "Open-door rehearsal",
  },
  {
    name: "The Rust Pit",
    short: "Basement bar",
    district: "SECTOR 09 · BELOW STREET LEVEL",
    tag: "LOCAL DISTURBANCE",
    fans: 100,
    gear: 8,
    duration: 900,
    credits: 2400,
    reward: 250,
    description: "Sticky floors, exposed wires, and your first real crowd.",
    gig: "Basement takeover",
  },
  {
    name: "Club Dead Signal",
    short: "Underground club",
    district: "SECTOR 12 · THE NIGHT MARKET",
    tag: "UNDERGROUND FREQUENCY",
    fans: 1500,
    gear: 25,
    duration: 3600,
    credits: 25000,
    reward: 1800,
    description: "They came for the blackout. They stayed for the breakdown.",
    gig: "Dead Signal residency",
  },
  {
    name: "Foundry 404",
    short: "Industrial warehouse",
    district: "SECTOR 18 · THE IRON BELT",
    tag: "CULT FOLLOWING",
    fans: 12000,
    gear: 50,
    duration: 14400,
    credits: 220000,
    reward: 9000,
    description: "The assembly line is dead. The mosh pit is very much alive.",
    gig: "Foundry riot",
  },
  {
    name: "The Monolith",
    short: "Corporate arena",
    district: "UPPER CITY · CORPORATE ZONE",
    tag: "SYSTEM-WIDE THREAT",
    fans: 55000,
    gear: 85,
    duration: 43200,
    credits: 1800000,
    reward: 35000,
    description: "Their name on the building. Your noise in every corner.",
    gig: "Monolith headline",
  },
  {
    name: "Orbital Uplink",
    short: "Orbital broadcast",
    district: "LOW ORBIT · UNLICENSED FREQUENCY",
    tag: "BEYOND THE MEGACITY",
    fans: 160000,
    gear: 125,
    duration: 64800,
    credits: 15000000,
    reward: 100000,
    description: "No atmosphere. No limits. The whole planet is listening.",
    gig: "Planetwide transmission",
  },
];
export const ALBUMS = [
  {
    name: "Static in the Wires",
    kind: "DEBUT DEMO",
    fans: 0,
    cost: 500,
    duration: 600,
    reward: 100,
    royalty: 2,
    color: "#9ead70",
  },
  {
    name: "Concrete Cathedral",
    kind: "UNDERGROUND EP",
    fans: 500,
    cost: 8000,
    duration: 3600,
    reward: 700,
    royalty: 15,
    color: "#5dafaf",
  },
  {
    name: "Chrome Is a Disease",
    kind: "DEBUT ALBUM",
    fans: 3000,
    cost: 90000,
    duration: 14400,
    reward: 3000,
    royalty: 90,
    color: "#bb8c77",
  },
  {
    name: "No Gods / Only Noise",
    kind: "SECOND ALBUM",
    fans: 15000,
    cost: 800000,
    duration: 28800,
    reward: 10000,
    royalty: 500,
    color: "#b199ce",
  },
  {
    name: "Kill the Algorithm",
    kind: "DOUBLE ALBUM",
    fans: 45000,
    cost: 6000000,
    duration: 43200,
    reward: 30000,
    royalty: 2500,
    color: "#e2be5b",
  },
  {
    name: "Earth Is the Opening Act",
    kind: "ORBITAL RELEASE",
    fans: 110000,
    cost: 40000000,
    duration: 64800,
    reward: 65000,
    royalty: 12000,
    color: "#83c7d6",
  },
];
export const ACHIEVEMENTS = [
  {
    id: "first-riff",
    name: "Hello, noise.",
    description: "Play your first riff.",
  },
  {
    id: "hundred-riffs",
    name: "Calloused fingers",
    description: "Play 100 riffs.",
  },
  {
    id: "first-recruit",
    name: "Better together",
    description: "Recruit your first bandmate.",
  },
  {
    id: "full-band",
    name: "Five against the city",
    description: "Fill all four band slots.",
  },
  {
    id: "first-show",
    name: "You had to be there",
    description: "Finish your first gig.",
  },
  {
    id: "first-album",
    name: "On the record",
    description: "Release your first album.",
  },
  {
    id: "thousand-fans",
    name: "An underground following",
    description: "Reach 1,000 fans.",
  },
  {
    id: "orbital",
    name: "The planet is listening",
    description: "Complete an orbital headline show.",
  },
  {
    id: "legend",
    name: "Legends never unplug",
    description: "Start a new era.",
  },
];
